export default {
  GET_ALL_PATIENT_SUCCESS : 'GET_ALL_PATIENT_SUCCESS',
  GET_ALL_PATIENT_FAILURE : 'GET_ALL_PATIENT_FAILURE',
  SEARCH_PATIENT_SUCCESS  : 'SEARCH_PATIENT_SUCCESS',
  SEARCH_PATIENT_FAILURE  : 'SEARCH_PATIENT_FAILURE',
  FILTER_PATIENT_BY_STATUS: 'FILTER_PATIENT_BY_STATUS',
  FILTER_PATIENT_BY_TIME: 'FILTER_PATIENT_BY_TIME',
  GET_PATIENT_DETAIL_SUCCESS: 'GET_PATIENT_DETAIL_SUCCESS',
  GET_PATIENT_DETAIL_FAILURE: 'GET_PATIENT_DETAIL_FAILURE',
}
